# Generated by Django 5.2.15 on 2026-07-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
