# Generated by Django 5.2.15 on 2026-07-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0002_userdetail_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='role',
            field=models.CharField(blank=True, default='user', max_length=50, null=True),
        ),
    ]
