# Generated by Django 5.2.15 on 2026-07-25 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0004_dept_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('dept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='depts', to='civicconnectapp.dept')),
            ],
        ),
    ]
