# Generated by Django 5.2.15 on 2026-07-25 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0005_deptdetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=250, null=True)),
                ('dept_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_details', to='civicconnectapp.deptdetails')),
                ('user_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deptemps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
