# Generated by Django 5.2.15 on 2026-08-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0006_deptemployees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='location',
        ),
        migrations.AddField(
            model_name='deptdetails',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
