# Generated by Django 5.2.15 on 2026-08-05 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0007_remove_dept_location_deptdetails_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deptdetails',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deptdetails',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deptdetails',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='civicconnectapp.dept'),
        ),
        migrations.AlterField(
            model_name='deptdetails',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
