# Generated by Django 5.2.15 on 2026-08-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0008_deptdetails_created_at_deptdetails_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptdetails',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deptdetails',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='deptdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='deptdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='deptdetails',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
