# Generated by Django 5.2.15 on 2026-08-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0009_deptdetails_latitude_deptdetails_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deptdetails',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='deptdetails',
            name='longitude',
        ),
        migrations.AddField(
            model_name='deptdetails',
            name='urls',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deptdetails',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
