# Generated by Django 5.2.15 on 2026-08-06 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0010_remove_deptdetails_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptdetails',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='civicconnectapp.district'),
        ),
    ]
