# Generated by Django 5.2.15 on 2026-08-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0012_alter_userdetail_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptdetails',
            name='password',
            field=models.CharField(blank=True, null=True),
        ),
    ]
