# Generated by Django 5.2.15 on 2026-08-12 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0014_deptdetails_is_active_complaint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deptdetails',
            name='password',
        ),
        migrations.AddField(
            model_name='deptemployees',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='deptemployees',
            name='dept_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='civicconnectapp.deptdetails'),
        ),
        migrations.AlterField(
            model_name='deptemployees',
            name='user_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dept_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DeptUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_users', to='civicconnectapp.dept')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dept_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
