# Generated by Django 5.2.15 on 2026-08-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0016_remove_deptemployees_is_active_deptdetails_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptdetails',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
