# Generated by Django 5.2.15 on 2026-08-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0018_dept_email_dept_is_active_dept_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptdetails',
            name='placename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
