# Generated by Django 5.2.15 on 2026-08-16 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0019_deptdetails_placename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('GRAMA_PANCHAYAT', 'Grama Panchayat'), ('BLOCK_PANCHAYAT', 'Block Panchayat'), ('DISTRICT_PANCHAYAT', 'District Panchayat'), ('MUNICIPALITY', 'Municipality'), ('CORPORATION', 'Corporation'), ('LEGISLATIVE_ASSEMBLY', 'Kerala Legislative Assembly'), ('LOK_SABHA', 'Lok Sabha')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('taluk', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='civicconnectapp.district')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='civicconnectapp.constituency')),
            ],
            options={
                'db_table': 'constituencies',
                'ordering': ['type', 'name'],
                'indexes': [models.Index(fields=['type'], name='constituenc_type_d4d675_idx'), models.Index(fields=['district'], name='constituenc_distric_a1560f_idx'), models.Index(fields=['is_active'], name='constituenc_is_acti_0a4272_idx')],
            },
        ),
    ]
