# Generated by Django 5.2.15 on 2026-08-16 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0020_constituency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constituency',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='constituency',
            name='constituenc_type_d4d675_idx',
        ),
        migrations.RemoveIndex(
            model_name='constituency',
            name='constituenc_distric_a1560f_idx',
        ),
        migrations.RemoveIndex(
            model_name='constituency',
            name='constituenc_is_acti_0a4272_idx',
        ),
        migrations.RemoveField(
            model_name='constituency',
            name='code',
        ),
        migrations.RemoveField(
            model_name='constituency',
            name='description',
        ),
        migrations.RemoveField(
            model_name='constituency',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='constituency',
            name='taluk',
        ),
        migrations.AddField(
            model_name='constituency',
            name='representative',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='represented_constituency', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='constituency',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to='civicconnectapp.district'),
        ),
        migrations.AlterModelTable(
            name='constituency',
            table=None,
        ),
    ]
