# Generated by Django 5.2.15 on 2026-08-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0021_alter_constituency_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='ward_name_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
