# Generated by Django 5.2.15 on 2026-08-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0022_constituency_ward_name_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='type',
            field=models.CharField(choices=[('GRAMA_PANCHAYAT', 'Grama Panchayat'), ('BLOCK_PANCHAYAT', 'Block Panchayat'), ('DISTRICT_PANCHAYAT', 'District Panchayat'), ('MUNICIPALITY', 'Municipality'), ('CORPORATION', 'Corporation'), ('LEGISLATIVE_ASSEMBLY', 'Niyama Sabha'), ('LOK_SABHA', 'Lok Sabha')], max_length=30),
        ),
    ]
