# Generated by Django 5.2.15 on 2026-08-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0024_representative'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Representative',
        ),
    ]
