# Generated by Django 5.2.15 on 2026-08-18 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0025_delete_representative'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='civicconnectapp.constituency')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='representative', to='civicconnectapp.userdetail')),
            ],
        ),
    ]
