# Generated by Django 5.2.15 on 2026-08-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0026_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
