# Generated by Django 5.2.15 on 2026-08-18 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0027_representative_end_date_representative_is_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representatives', to='civicconnectapp.constituency'),
        ),
    ]
