# Generated by Django 5.2.15 on 2026-08-20 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0028_alter_representative_constituency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deptdetails',
            old_name='region',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='dept',
            name='email',
        ),
        migrations.RemoveField(
            model_name='dept',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='dept',
            name='password',
        ),
        migrations.RemoveField(
            model_name='deptdetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='deptdetails',
            name='password',
        ),
        migrations.AddField(
            model_name='dept',
            name='deptadv',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dept',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='civicconnectapp.userdetail'),
        ),
    ]
