# Generated by Django 5.2.15 on 2026-08-27 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0030_branch_delete_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='user_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branchuser', to='civicconnectapp.userdetail'),
        ),
    ]
