# Generated by Django 5.2.15 on 2026-08-27 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0031_alter_branch_user_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='user_details',
            new_name='user_id',
        ),
    ]
