# Generated by Django 5.2.15 on 2026-08-27 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0032_rename_user_details_branch_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='user_id',
            new_name='user_details',
        ),
    ]
