# Generated by Django 5.2.15 on 2026-08-27 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0033_rename_user_id_branch_user_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptemployees',
            name='dept_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deptemployee', to='civicconnectapp.dept'),
        ),
        migrations.AddField(
            model_name='dept',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dept',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='civicconnectapp.district'),
        ),
        migrations.AddField(
            model_name='dept',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dept',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dept',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dept',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='dept',
            name='placename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dept',
            name='urls',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dept',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DeptDetails',
        ),
    ]
