# Generated by Django 5.2.15 on 2026-08-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0034_alter_deptemployees_dept_details_dept_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='district',
        ),
    ]
