# Generated by Django 5.2.15 on 2026-08-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0035_remove_dept_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='is_verified',
        ),
    ]
