# Generated by Django 5.2.15 on 2026-08-30 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0036_remove_dept_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituency',
            name='representative',
        ),
    ]
