# Generated by Django 5.2.15 on 2026-08-30 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0037_remove_constituency_representative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constituency', to='civicconnectapp.constituency'),
        ),
    ]
