# Generated by Django 5.2.15 on 2026-08-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0038_alter_representative_constituency'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
