# Generated by Django 5.2.15 on 2026-08-30 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0039_representative_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=250, null=True)),
                ('branch_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branchemployee', to='civicconnectapp.branch')),
                ('user_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deptemps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DeptEmployees',
        ),
    ]
