# Generated by Django 5.2.15 on 2026-08-30 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0040_branchemployees_delete_deptemployees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchemployees',
            name='branch_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branchdetails', to='civicconnectapp.branch'),
        ),
        migrations.AlterField(
            model_name='branchemployees',
            name='user_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branchemps', to=settings.AUTH_USER_MODEL),
        ),
    ]
