# Generated by Django 5.2.15 on 2026-08-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0041_alter_branchemployees_branch_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchemployees',
            old_name='role',
            new_name='branch_role',
        ),
    ]
