# Generated by Django 5.2.15 on 2026-09-01 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0044_branch_latitude_branch_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_constituencies', to='civicconnectapp.constituency'),
        ),
    ]
