# Generated by Django 5.2.15 on 2026-09-01 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0045_constituency_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constituency',
            old_name='parent',
            new_name='parent_constituency',
        ),
    ]
