# Generated by Django 5.2.15 on 2026-09-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0046_rename_parent_constituency_parent_constituency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintresponse',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='complaintassignment',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='complaintsupport',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='complaintattachment',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='complaintassignment',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='complaintassignment',
            name='assigned_employee',
        ),
        migrations.RemoveField(
            model_name='complaintassignment',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='complaintassignment',
            name='reassigned_from',
        ),
        migrations.RemoveField(
            model_name='complaintattachment',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='complaintresponse',
            name='responded_by',
        ),
        migrations.RemoveField(
            model_name='complaintresponseattachment',
            name='response',
        ),
        migrations.RemoveField(
            model_name='complaintsupport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='branchemployees',
            name='branch_role',
        ),
        migrations.RemoveField(
            model_name='constituency',
            name='parent_constituency',
        ),
        migrations.AddField(
            model_name='branchemployees',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='ComplaintAssignment',
        ),
        migrations.DeleteModel(
            name='ComplaintAttachment',
        ),
        migrations.DeleteModel(
            name='ComplaintResponse',
        ),
        migrations.DeleteModel(
            name='ComplaintResponseAttachment',
        ),
        migrations.DeleteModel(
            name='ComplaintSupport',
        ),
    ]
