# Generated by Django 5.2.15 on 2026-09-03 10:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0047_remove_complaintresponse_complaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='location_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='constituency',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
