# Generated by Django 5.2.15 on 2026-09-03 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0049_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='civicconnectapp.representative'),
        ),
    ]
