# Generated by Django 5.2.15 on 2026-09-04 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0050_complaint_representative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to='civicconnectapp.district'),
        ),
    ]
