# Generated by Django 5.2.15 on 2026-09-06 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0051_alter_constituency_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='complaint_attachments/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('other', 'Other')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Complaint Categories',
            },
        ),
        migrations.CreateModel(
            name='ComplaintEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('delayed', 'Delayed Response'), ('unsatisfactory', 'Unsatisfactory Action'), ('reassignment', 'Reassignment Needed'), ('urgency', 'High Urgency'), ('other', 'Other')], max_length=50)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('would_recommend', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ml', 'Malayalam')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('translated_at', models.DateTimeField(auto_now_add=True)),
                ('translated_by', models.CharField(default='auto', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LocalBodyRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('ward_member', 'Ward Member'), ('ward_member_open', 'Ward Member (Open)'), ('ward_member_reserved', 'Ward Member (Reserved)'), ('president', 'President/Chairperson'), ('vice_president', 'Vice President/Vice Chairperson')], default='ward_member', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='branchemployees',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='complaint_audio/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='civicconnectapp.constituency'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='original_language',
            field=models.CharField(choices=[('en', 'English'), ('ml', 'Malayalam')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='voice_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ml', 'Malayalam')], default='en', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ml', 'Malayalam')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='constituency',
            index=models.Index(fields=['type', 'district'], name='civicconnec_type_2f883b_idx'),
        ),
        migrations.AddIndex(
            model_name='constituency',
            index=models.Index(fields=['name'], name='civicconnec_name_63fcc0_idx'),
        ),
        migrations.AddField(
            model_name='complaintattachment',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='civicconnectapp.complaint'),
        ),
        migrations.AddField(
            model_name='complaintattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='civicconnectapp.complaintcategory'),
        ),
        migrations.AddField(
            model_name='complaintescalation',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='civicconnectapp.complaint'),
        ),
        migrations.AddField(
            model_name='complaintescalation',
            name='escalated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaintescalation',
            name='escalated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaintfeedback',
            name='complaint',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='civicconnectapp.complaint'),
        ),
        migrations.AddField(
            model_name='complaintlike',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='civicconnectapp.complaint'),
        ),
        migrations.AddField(
            model_name='complaintlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complainttranslation',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='civicconnectapp.complaint'),
        ),
        migrations.AddField(
            model_name='localbodyrepresentative',
            name='constituency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_body_representatives', to='civicconnectapp.constituency'),
        ),
        migrations.AddField(
            model_name='localbodyrepresentative',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_body_representative', to='civicconnectapp.userdetail'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='local_body_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='civicconnectapp.localbodyrepresentative'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', 'created_at'], name='civicconnec_status_093031_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['citizen', 'created_at'], name='civicconnec_citizen_bc03c2_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['constituency'], name='civicconnec_constit_74ea03_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='complaintlike',
            unique_together={('complaint', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='complainttranslation',
            unique_together={('complaint', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='localbodyrepresentative',
            unique_together={('user_profile', 'constituency', 'designation')},
        ),
    ]
