# Generated by Django 5.2.15 on 2026-09-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0052_complaintattachment_complaintcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='voice_processing_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default=None, help_text='Status of voice transcription/translation processing', max_length=20, null=True),
        ),
    ]
