# Generated by Django 5.2.15 on 2026-09-13 09:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0053_complaint_voice_processing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localbodyrepresentative',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='localbodyrepresentative',
            name='designation',
            field=models.CharField(blank=True, choices=[('ward_member', 'Ward Member'), ('ward_member_open', 'Ward Member (Open)'), ('ward_member_reserved', 'Ward Member (Reserved)'), ('president', 'President/Chairperson'), ('vice_president', 'Vice President/Vice Chairperson')], default='ward_member', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='localbodyrepresentative',
            name='is_current',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='localbodyrepresentative',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='localbodyrepresentative',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_body_representative', to='civicconnectapp.userdetail'),
        ),
        migrations.CreateModel(
            name='LocalBodyConstituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=200)),
                ('ward_number', models.CharField(blank=True, max_length=50, null=True)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='civicconnectapp.constituency')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='localbodyrepresentative',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='localbodyrepresentative',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='civicconnectapp.localbodyconstituency'),
        ),
        migrations.AlterUniqueTogether(
            name='localbodyrepresentative',
            unique_together={('user_profile', 'ward', 'designation')},
        ),
        migrations.AddIndex(
            model_name='localbodyconstituency',
            index=models.Index(fields=['local_body', 'ward_number'], name='civicconnec_local_b_87bbe3_idx'),
        ),
        migrations.AddIndex(
            model_name='localbodyconstituency',
            index=models.Index(fields=['ward_name'], name='civicconnec_ward_na_898dc7_idx'),
        ),
        migrations.AddConstraint(
            model_name='localbodyconstituency',
            constraint=models.UniqueConstraint(fields=('local_body', 'ward_number'), name='unique_ward_per_local_body'),
        ),
        migrations.RemoveField(
            model_name='localbodyrepresentative',
            name='constituency',
        ),
    ]
