# Generated by Django 5.2.15 on 2026-09-14 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0054_alter_localbodyrepresentative_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='civicconnectapp.branchemployees'),
        ),
    ]
