# Generated by Django 5.2.15 on 2026-09-15 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0055_complaint_assigned_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='civicconnectapp.complaint')),
                ('representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_responses', to='civicconnectapp.representative')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['complaint', '-created_at'], name='civicconnec_complai_560854_idx')],
            },
        ),
    ]
