# Generated by Django 5.2.15 on 2026-09-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0057_complaintresponseattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchemployees',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
