# Generated by Django 5.2.15 on 2026-09-18 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0058_branchemployees_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintresponse',
            name='branch_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_responses', to='civicconnectapp.branchemployees'),
        ),
    ]
