# Generated by Django 5.2.15 on 2026-09-21 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0060_mywardcomplaintshare_mywardpost_mywardpostattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyWardDisasterVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('verified', 'Verified'), ('not_verified', 'Not Verified')], max_length=20)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='mywardpost',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mywardpost',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='mywardpost',
            index=models.Index(fields=['post_type', 'created_at'], name='civicconnec_post_ty_fadf9d_idx'),
        ),
        migrations.AddIndex(
            model_name='mywardpost',
            index=models.Index(fields=['ward', 'post_type'], name='civicconnec_ward_id_623af7_idx'),
        ),
        migrations.AddField(
            model_name='mywarddisasterverification',
            name='disaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disaster_verifications', to='civicconnectapp.mywardpost'),
        ),
        migrations.AddField(
            model_name='mywarddisasterverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myward_disaster_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mywarddisasterverification',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disaster_verifications', to='civicconnectapp.localbodyconstituency'),
        ),
        migrations.AddConstraint(
            model_name='mywarddisasterverification',
            constraint=models.UniqueConstraint(fields=('disaster', 'user'), name='unique_disaster_vote_per_user'),
        ),
    ]
