# Generated by Django 5.2.15 on 2026-09-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0062_mywarddisasterauthorityreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mywarddisasterauthorityreview',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='mywarddisasterauthorityreview',
            name='unique_authority_review_per_disaster',
        ),
        migrations.AlterField(
            model_name='mywarddisasterauthorityreview',
            name='is_verified',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
