# Generated by Django 5.2.15 on 2026-09-27 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnectapp', '0063_alter_mywarddisasterauthorityreview_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mywardpost',
            name='approval_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myward_post_approvals', to='civicconnectapp.branch'),
        ),
        migrations.AddField(
            model_name='mywardpost',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='mywardpost',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mywardpost',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mywardpost',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_myward_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mywardpost',
            name='submitted_by_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_myward_posts', to='civicconnectapp.branchemployees'),
        ),
        migrations.AlterField(
            model_name='mywardpost',
            name='author_type',
            field=models.CharField(choices=[('user', 'User'), ('branch', 'Branch'), ('representative', 'Representative'), ('branch_employee', 'Branch Employee')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='mywardpost',
            index=models.Index(fields=['approval_status', 'created_at'], name='civicconnec_approva_4421c1_idx'),
        ),
        migrations.AddIndex(
            model_name='mywardpost',
            index=models.Index(fields=['approval_branch', 'approval_status'], name='civicconnec_approva_8ace36_idx'),
        ),
    ]
